### ISSUE TITLE
Look into supporting ZMQ::FFI backend

### ISSUE THREAD

**Issue by zmughal** [zmughal/p5-Net-Async-ZMQ#3]
- Use [`->get` or `->get_fd`](https://metacpan.org/pod/ZMQ::FFI#get1) to retrieve socket file handle.

**Comment by JonnoFTW** [comment]
Will this upgrade be pushed to CPAN?

**Comment by zmughal** [comment]
I've been waiting on <https://github.com/zeromq/perlzmq/pull/44>, but I'll go ahead now!

**Comment by zmughal** [comment]
[Net-Async-ZMQ-0.002](https://metacpan.org/release/ZMUGHAL/Net-Async-ZMQ-0.002) is now headed to CPAN with these changes.
